version: '3'
services:
    db:
        container_name: nordic_car_db
        image: mysql:8.2.0
        ports:
            - "${MYSQL_PORT:-8001}:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_USER: ${MYSQL_USER:-app}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
        volumes:
            - ./docker/db:/var/lib/mysql:rw
        networks:
            - nordic_car_network

    app:
        container_name: nordic_car_app
        image: daalvand/nordic_car:latest
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - nordic_car_network

    nginx:
        container_name: nordic_car_nginx
        image: nginx:1.25-alpine
        ports:
            - "${SERVER_PORT:-8000}:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - nordic_car_network

networks:
    nordic_car_network:
        driver: bridge
