name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push php app
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/wallet_api:latest

  run-tests:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: daalvand/wallet_api:latest
    steps:
      - name: install dependencies
        run: /usr/local/bin/composer install
        working-directory: /var/www/html
      - name: create database file
        run: touch database/database.sqlite
        working-directory: /var/www/html
      - name: Run tests
        run: php artisan test
        working-directory: /var/www/html
